language: php

php:
  - "5.5"

sudo: false

before_script: 
  - npm install -g grunt-cli
  - npm install

script: npm run-script ci

env:
  - JQUERIES=1.8.3
  - JQUERIES=1.11.1
  - JQUERIES=2.1.1
  - JQUERIES=git
  - CITYPE=demos

notifications:
  irc:
    channels:
      - "chat.freenode.net#jqueryui-dev"
